name: Docker Image CI

on:
  push:
    branches: [ main ]
  create:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Extract the version tag
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag subversion-httpd-ubuntu2004:${{steps.vars.outputs.tag}}
