name: Docker Image Build and Push

# runs only for PR on branch main
on:
  push:
    branches:
      - main

env:
  # TODO: Creates container named ACCOUNT/REPO
  #       Append /IMAGE-NAME to create a container named ACCOUNT/REPO/IMAGE-NAME
  IMAGE_NAME: ${{ github.repository }}

  # Registry.
  REGISTRY: docker.io

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Get sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}

  # Push image to Docker Hub
  push:
    # Ensure build job passes before pushing image.
    needs: build

    runs-on: ubuntu-20.04

    steps:
      - name: Get sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}

      - name: Push the Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.semVer }}
